# Generated by Django 6.0.3 on 2026-03-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (5, 'Deleted')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (5, 'Deleted')], default=1)),
            ],
        ),
    ]
